// Matt's shelf — everything he's read (and is reading), pulled from his Goodreads export.
// `yearRead` shows a "Read 2025" badge; `reading: true` shows "Reading now";
// `rating` (1-5, his own Goodreads stars) drives the default sort.
const MY_BOOKS = [
  // — Red Rising saga —
  { id: 'red-rising', title: 'Red Rising', author: 'Pierce Brown', genre: 'Science Fiction', year: 2014, yearRead: 2025, isbn: '9780345539786', rating: 4,
    summary: 'A Red miner of Mars infiltrates the ruling Golds to burn their society down from the inside.',
    why: 'Ender meets Rome — the series everyone in tech is secretly reading. Start here.' },
  { id: 'golden-son', title: 'Golden Son', author: 'Pierce Brown', genre: 'Science Fiction', year: 2015, yearRead: 2025, isbn: '9780345539816', rating: 4,
    summary: 'Darrow rises through Gold society as civil war ignites across the solar system.',
    why: 'The rare book two that outdoes book one — betrayals land like body blows.' },
  { id: 'morning-star', title: 'Morning Star', author: 'Pierce Brown', genre: 'Science Fiction', year: 2016, yearRead: 2025, isbn: '9780345539847', rating: 4,
    summary: 'The Rising comes to a head as Darrow leads open rebellion against the Sovereign.',
    why: 'A finale that actually delivers — the original trilogy sticks the landing.' },
  { id: 'iron-gold', title: 'Iron Gold', author: 'Pierce Brown', genre: 'Science Fiction', year: 2018, yearRead: 2025, isbn: '9780425285916', rating: 3,
    summary: 'Ten years after the Rising, the new republic frays across four points of view.',
    why: 'What happens after the revolution wins — messier, darker, more ambitious.' },
  { id: 'dark-age', title: 'Dark Age', author: 'Pierce Brown', genre: 'Science Fiction', year: 2019, yearRead: 2025, isbn: '9780425285930', rating: 4,
    summary: 'War consumes Mars and Mercury in the saga’s most brutal installment.',
    why: 'Relentless and jaw-dropping — Brown at maximum intensity.' },
  { id: 'light-bringer', title: 'Light Bringer', author: 'Pierce Brown', genre: 'Science Fiction', year: 2023, yearRead: 2026, isbn: '9780425285978', rating: 4,
    summary: 'Darrow finds his way back to himself on the long road to a final reckoning with Atlas.',
    why: 'The series regains its soul — sets up the finale perfectly.' },

  // — Dungeon Crawler Carl —
  { id: 'dungeon-crawler-carl', title: 'Dungeon Crawler Carl', author: 'Matt Dinniman', genre: 'LitRPG', year: 2020, yearRead: 2025, coverId: 15143022, rating: 5,
    summary: 'Earth is demolished for an intergalactic reality-show dungeon; Carl and his ex’s cat fight through it live.',
    why: 'The funniest, angriest thing in sci-fi right now — a word-of-mouth phenomenon for a reason.' },
  { id: 'carls-doomsday-scenario', title: 'Carl’s Doomsday Scenario', author: 'Matt Dinniman', genre: 'LitRPG', year: 2020, yearRead: 2025, coverId: 11702962, rating: 4,
    summary: 'Carl and Donut hit the third floor and start weaponizing the dungeon’s own rules.',
    why: 'The satire sharpens and the game gets rigged — in both directions.' },
  { id: 'dungeon-anarchists-cookbook', title: 'The Dungeon Anarchist’s Cookbook', author: 'Matt Dinniman', genre: 'LitRPG', year: 2021, yearRead: 2025, coverId: 15233609, rating: 5,
    summary: 'The subway-line floor turns the crawl into full guerrilla warfare against the system.',
    why: 'Where the series reveals it has a plan — and a heart.' },
  { id: 'gate-of-the-feral-gods', title: 'The Gate of the Feral Gods', author: 'Matt Dinniman', genre: 'LitRPG', year: 2021, yearRead: 2025, coverId: 15232581, rating: 4,
    summary: 'Castles, submarines, and bubble-dwelling gods on a floor built to break parties.',
    why: 'Peak chaos-engineering from Carl — and Donut steals every scene.' },
  { id: 'butchers-masquerade', title: 'The Butcher’s Masquerade', author: 'Matt Dinniman', genre: 'LitRPG', year: 2022, yearRead: 2025, coverId: 15231958, rating: 5,
    summary: 'The hunting-ground floor invites the galaxy’s elite to hunt crawlers — badly, it turns out.',
    why: 'Fan-favorite for a reason: the masquerade sequence is an all-timer.' },
  { id: 'eye-of-the-bedlam-bride', title: 'The Eye of the Bedlam Bride', author: 'Matt Dinniman', genre: 'LitRPG', year: 2023, yearRead: 2025, coverId: 15231488, rating: 4,
    summary: 'Carl faces the faction wars while a reality-warping god takes a personal interest.',
    why: 'The stakes go cosmic without losing the jokes.' },
  { id: 'this-inevitable-ruin', title: 'This Inevitable Ruin', author: 'Matt Dinniman', genre: 'LitRPG', year: 2024, yearRead: 2025, coverId: 15142977, rating: 4,
    summary: 'The war floor: every faction, every grudge, and Carl’s long game all collide.',
    why: 'The series’ biggest swing yet — and it connects.' },
  { id: 'parade-of-horribles', title: 'A Parade of Horribles', author: 'Matt Dinniman', genre: 'LitRPG', year: 2026, yearRead: 2026, rating: 4,
    summary: 'The crawl barrels toward its endgame as the ninth floor opens.',
    why: 'Book eight of the crawl — the end is in sight.' },

  // — Bobiverse —
  { id: 'we-are-legion', title: 'We Are Legion (We Are Bob)', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2016, yearRead: 2025, isbn: '9781680680584', rating: 5,
    summary: 'A software engineer wakes up as a self-replicating space probe and starts forking.',
    why: 'The most engineer-brained sci-fi ever written — every dev sees themselves in Bob.' },
  { id: 'for-we-are-many', title: 'For We Are Many', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2017, yearRead: 2025, coverId: 11329842, rating: 4,
    summary: 'The Bobs spread across star systems while an alien threat starts eating colonies.',
    why: 'Scaling problems, literally — the Bobiverse grows up.' },
  { id: 'all-these-worlds', title: 'All These Worlds', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2017, yearRead: 2026, coverId: 12750210, rating: 4,
    summary: 'The war with the Others comes to a head as humanity’s last colonies hang in the balance.',
    why: 'Closes the first arc with a genuinely satisfying engineering victory.' },
  { id: 'heavens-river', title: 'Heaven’s River', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2020, yearRead: 2026, coverId: 10522898, rating: 5,
    summary: 'A rescue mission inside a 900-million-mile megastructure tests what the Bobs have become.',
    why: 'Big Dumb Object sci-fi done right, with a civil war brewing among the Bobs themselves.' },
  { id: 'not-till-we-are-lost', title: 'Not Till We Are Lost', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2024, yearRead: 2026, coverId: 14926951,
    summary: 'The Bobs scatter to new frontiers as humanity’s diaspora hits growing pains.',
    why: 'The Bobiverse keeps finding new problems worth solving.' },

  // — Empyrean —
  { id: 'fourth-wing', title: 'Fourth Wing', author: 'Rebecca Yarros', genre: 'Fantasy', year: 2023, yearRead: 2025, isbn: '9781649374042',
    summary: 'A fragile scribe is forced into a war college where dragon riders are made — or killed.',
    why: 'The romantasy juggernaut — read it to understand what took over publishing.' },
  { id: 'iron-flame', title: 'Iron Flame', author: 'Rebecca Yarros', genre: 'Fantasy', year: 2023, yearRead: 2025, isbn: '9781649374172',
    summary: 'Violet learns the war she trained for is built on lies — and the real enemy is older.',
    why: 'Doubles down on the conspiracies behind the dragons.' },
  { id: 'onyx-storm', title: 'Onyx Storm', author: 'Rebecca Yarros', genre: 'Fantasy', year: 2025, yearRead: 2025, isbn: '9781649374189',
    summary: 'Violet hunts allies beyond the wards while everything at Basgiath unravels.',
    why: 'The biggest launch in publishing history — and a cliffhanger to match.' },

  // — Mistborn —
  { id: 'mistborn', title: 'Mistborn: The Final Empire', author: 'Brandon Sanderson', genre: 'Fantasy', year: 2006, yearRead: 2026, isbn: '9780765350381', rating: 5,
    summary: 'A street thief discovers she’s Mistborn and joins a crew planning to rob and topple an immortal god-emperor.',
    why: 'The best magic system in fantasy plus an Ocean’s Eleven heist — Sanderson’s perfect entry point.' },
  { id: 'well-of-ascension', title: 'The Well of Ascension', author: 'Brandon Sanderson', genre: 'Fantasy', year: 2007, yearRead: 2026, isbn: '9780765356130', rating: 4,
    summary: 'The crew won — now they have to govern, under siege from three armies at once.',
    why: 'What happens after you win the revolution — the founder’s dilemma in fantasy form.' },
  { id: 'hero-of-ages', title: 'The Hero of Ages', author: 'Brandon Sanderson', genre: 'Fantasy', year: 2008, reading: true, isbn: '9780765356147',
    summary: 'The world itself is ending, and every clue from two books snaps into place.',
    why: 'One of the great endings in fantasy — every setup pays off.' },

  // — Throne of Glass —
  { id: 'throne-of-glass', title: 'Throne of Glass', author: 'Sarah J. Maas', genre: 'Fantasy', year: 2012, yearRead: 2026, isbn: '9781619630345',
    summary: 'An imprisoned assassin competes to become the king’s champion while something stalks the castle.',
    why: 'The series that built Maas’s empire — starts fun, goes epic.' },
  { id: 'crown-of-midnight', title: 'Crown of Midnight', author: 'Sarah J. Maas', genre: 'Fantasy', year: 2013, reading: true, isbn: '9781619630628',
    summary: 'Celaena serves the king she despises while keeping deadly secrets from everyone she loves.',
    why: 'Where the series shows its real cards — the twist recontextualizes everything.' },

  // — standalones & classics —
  { id: 'project-hail-mary', title: 'Project Hail Mary', author: 'Andy Weir', genre: 'Science Fiction', year: 2021, yearRead: 2026, isbn: '9780593135204', rating: 5,
    summary: 'A lone astronaut wakes with amnesia on a last-ditch mission to save the sun — and finds an unlikely ally.',
    why: 'The most-recommended novel in tech since The Martian — problem-solving as a love language.' },
  { id: 'dark-matter', title: 'Dark Matter', author: 'Blake Crouch', genre: 'Science Fiction', year: 2016, yearRead: 2025, isbn: '9781101904220',
    summary: 'A physics professor is abducted into the multiverse by the man he could have been.',
    why: 'A thriller about the roads not taken — every ambitious person’s what-if, weaponized.' },
  { id: 'hitchhikers-guide', title: 'The Hitchhiker’s Guide to the Galaxy', author: 'Douglas Adams', genre: 'Science Fiction', year: 1979, yearRead: 2025, isbn: '9780345391803', rating: 4,
    summary: 'Earth is demolished for a hyperspace bypass; Arthur Dent survives with a towel and a very unhelpful guidebook.',
    why: 'The founding text of engineer humor — Don’t Panic remains the best product advice ever shipped.' },
  { id: 'nineteen-eighty-four', title: '1984', author: 'George Orwell', genre: 'Classics', year: 1949, yearRead: 2025, isbn: '9780451524935', rating: 4,
    summary: 'Winston Smith commits the crime of thinking for himself inside a total surveillance state.',
    why: 'Still the sharpest lens on surveillance, language, and power — rereads differently every decade.' },
  { id: 'fellowship-of-the-ring', title: 'The Fellowship of the Ring', author: 'J.R.R. Tolkien', genre: 'Fantasy', year: 1954, yearRead: 2025, isbn: '9780547928210', rating: 4,
    summary: 'A hobbit inherits a ring that must be carried into the heart of enemy territory and destroyed.',
    why: 'The source code for all modern fantasy — everything since is a fork.' },
  { id: 'harry-potter-series', title: 'Harry Potter (complete series)', author: 'J.K. Rowling', genre: 'Fantasy', year: 1997, yearRead: 2025, isbn: '9780590353427', rating: 4,
    summary: 'Seven years at Hogwarts, from cupboard under the stairs to the Battle of Hogwarts.',
    why: 'The shared universe of an entire generation — worth rereading as an adult.' },
  { id: 'tomorrow-x3', title: 'Tomorrow, and Tomorrow, and Tomorrow', author: 'Gabrielle Zevin', genre: 'Literary Fiction', year: 2022, yearRead: 2025, coverId: 12859975, rating: 4,
    summary: 'Two friends build video games together across thirty years of love, grief, and creative partnership.',
    why: 'The best novel ever written about creative collaboration and shipping things with people you love.' },
  { id: 'atmosphere', title: 'Atmosphere', author: 'Taylor Jenkins Reid', genre: 'Literary Fiction', year: 2025, yearRead: 2026, coverId: 15098710, rating: 5,
    summary: 'A 1980s shuttle astronaut finds love and catastrophe in NASA’s golden age.',
    why: 'Reid turns the space program into her most emotional book yet.' },
  { id: 'lightlark', title: 'Lightlark', author: 'Alex Aster', genre: 'Fantasy', year: 2022, yearRead: 2026, coverId: 12917631,
    summary: 'Six cursed rulers compete in a deadly centennial game where only one curse can be broken.',
    why: 'The BookTok phenomenon that became a bidding war — a fast, twisty palate cleanser.' },
  { id: 'blood-over-bright-haven', title: 'Blood Over Bright Haven', author: 'M.L. Wang', genre: 'Fantasy', year: 2023, yearRead: 2026, coverId: 15090335, rating: 4,
    summary: 'The first woman admitted to a magical academy discovers the atrocity powering her city’s magic.',
    why: 'A standalone gut-punch about institutions and the cost of looking away — dark-academia done right.' },
  { id: 'end-the-fed', title: 'End the Fed', author: 'Ron Paul', genre: 'Economics', year: 2009, yearRead: 2026, coverId: 6255029, rating: 4,
    summary: 'Paul’s case against central banking: how the Federal Reserve distorts money, credit, and the business cycle.',
    why: 'Agree or not, it’s the argument behind half of crypto’s founding ethos.' },

  // — added from Matt's Goodreads export (2026-07) —
  { id: 'dune', title: 'Dune', author: 'Frank Herbert', genre: 'Science Fiction', year: 1965, isbn: '9780593099322', rating: 4,
    summary: 'Paul Atreides inherits a desert planet that controls the most valuable substance in the universe.',
    why: 'The best-selling sci-fi novel ever — politics, ecology, and empire in one book; a favorite of Musk and Bezos alike.' },
  { id: 'dune-messiah', title: 'Dune Messiah', author: 'Frank Herbert', genre: 'Science Fiction', year: 1969, isbn: '9780593098233', rating: 3,
    summary: 'Twelve years into Paul\u2019s reign, the jihad done in his name becomes a prison he cannot escape.',
    why: 'Herbert\u2019s deliberate answer to book one: what victory costs the victor.' },
  { id: 'three-body-problem', title: 'The Three-Body Problem', author: 'Liu Cixin', genre: 'Science Fiction', year: 2008, isbn: '9780765382030', rating: 5,
    summary: 'A signal sent to the stars during the Cultural Revolution invites a civilization with nothing to lose.',
    why: 'Obama and half of Silicon Valley recommend it — first contact as game theory at civilizational scale.' },
  { id: 'the-martian', title: 'The Martian', author: 'Andy Weir', genre: 'Science Fiction', year: 2011, isbn: '9780804139021', rating: 5,
    summary: 'An astronaut stranded on Mars sciences his way through every problem between him and rescue.',
    why: 'Pure engineering optimism — the book that made problem-solving a genre.' },
  { id: 'ready-player-one', title: 'Ready Player One', author: 'Ernest Cline', genre: 'Science Fiction', year: 2011, isbn: '9780307887436',
    summary: 'A global treasure hunt inside a virtual world where the prize is control of the OASIS itself.',
    why: 'The book every VR and metaverse pitch deck secretly references.' },
  { id: 'armada', title: 'Armada', author: 'Ernest Cline', genre: 'Science Fiction', year: 2015, isbn: '9780804137256',
    summary: 'A gamer discovers the alien-invasion game he\u2019s mastered is a training simulator for the real thing.',
    why: 'A popcorn homage to The Last Starfighter — fast, nostalgic fun.' },
  { id: 'artemis', title: 'Artemis', author: 'Andy Weir', genre: 'Science Fiction', year: 2017, isbn: '9780553448122',
    summary: 'A smuggler on the Moon\u2019s only city takes one job too big and has to out-engineer the fallout.',
    why: 'Weir\u2019s heist-on-the-Moon — lighter than his other books but built on the same real physics.' },
  { id: 'two-towers', title: 'The Two Towers', author: 'J.R.R. Tolkien', genre: 'Fantasy', year: 1954, isbn: '9780547928203', rating: 4,
    summary: 'The fellowship is broken: Rohan rides to war while Frodo follows a treacherous guide toward Mordor.',
    why: 'The middle passage that invented the epic-fantasy war story.' },
  { id: 'return-of-the-king', title: 'The Return of the King', author: 'J.R.R. Tolkien', genre: 'Fantasy', year: 1955, isbn: '9780547928197', rating: 4,
    summary: 'The war for Middle-earth ends at the Black Gate — and on the slopes of Mount Doom.',
    why: 'The ending every fantasy series since has been chasing.' },
  { id: 'operation-bounce-house', title: 'Operation Bounce House', author: 'Matt Dinniman', genre: 'LitRPG', year: 2026, yearRead: 2026, isbn: '9780593820308', rating: 3,
    summary: 'A standalone romp in the Dungeon Crawler Carl universe.',
    why: 'For DCC completionists waiting on the next main course.' },
  { id: 'eleven-twenty-two-sixty-three', title: '11/22/63', author: 'Stephen King', genre: 'Thriller', year: 2011, isbn: '9781451627282', rating: 4,
    summary: 'A teacher finds a doorway to 1958 and spends five years trying to stop the Kennedy assassination.',
    why: 'King\u2019s best-loved late-career book — time travel with real stakes and a broken heart.' },
  { id: 'girl-with-the-dragon-tattoo', title: 'The Girl with the Dragon Tattoo', author: 'Stieg Larsson', genre: 'Thriller', year: 2005, isbn: '9780307454546', rating: 4,
    summary: 'A disgraced journalist and a brilliant hacker unravel a forty-year-old disappearance in a family of industrialists.',
    why: 'The thriller that made forensic investigation cool — and Lisbeth Salander iconic.' },
  { id: 'subtle-art', title: 'The Subtle Art of Not Giving a F*ck', author: 'Mark Manson', genre: 'Self-Help', year: 2016, isbn: '9780062457714',
    summary: 'You have a finite number of f*cks to give — choose the few things worth caring about and let the rest go.',
    why: 'The anti-self-help book: values over positivity, chosen problems over comfort.' },
]

// Matt's to-be-read shelf — pulled from his Goodreads 'to-read' shelf (2026-07-21).
// Powers the bottom shelf in Shelf View. No rating/yearRead since these are unread.
const TO_READ_BOOKS = [
  { id: 'sea-of-tranquility-emily-st-john-mandel', title: 'Sea of Tranquility', author: 'Emily St. John Mandel', genre: 'Science Fiction', isbn: '9780593321447', toRead: true, summary: 'A time-travel investigation links a Canadian forest in 1912, a moon colony centuries later, and a strange anomaly that connects them all.' },
  { id: 'station-eleven-emily-st-john-mandel', title: 'Station Eleven', author: 'Emily St. John Mandel', genre: 'Science Fiction', isbn: '9780385353304', toRead: true, summary: 'Twenty years after a flu pandemic ends civilization, a traveling symphony performs Shakespeare for the settlements that remain.' },
  { id: 'starter-villain-john-scalzi', title: 'Starter Villain', author: 'John Scalzi', genre: 'Science Fiction', coverId: 13472546, toRead: true, summary: 'An unemployed substitute teacher inherits his estranged uncle’s supervillain business — volcano lair, hyper-intelligent cats, and all.' },
  { id: 'the-tainted-cup-robert-jackson-bennett', title: 'The Tainted Cup', author: 'Robert Jackson Bennett', genre: 'Fantasy', isbn: '9781984820709', toRead: true, summary: 'An investigator with an impossible memory and her eccentric superior probe a murder inside an empire defended by magically altered soldiers.' },
  { id: 'katabasis-r-f-kuang', title: 'Katabasis', author: 'R.F. Kuang', genre: 'Fantasy', isbn: '9780063021471', toRead: true, summary: 'Two rival Cambridge scholars descend into a bureaucratic vision of Hell to retrieve their dead advisor’s soul.' },
  { id: 'light-wielder-rachel-schneider', title: 'Light Wielder', author: 'Rachel Schneider', genre: 'Romantasy', toRead: true, summary: 'Book two of Fire & Metal, raising the stakes between rival magic-wielders forced to work together.' },
  { id: 'game-on-navessa-allen', title: 'Game On', author: 'Navessa Allen', genre: 'Romantasy', isbn: '9781638932277', toRead: true, summary: 'Book three of Into Darkness continues the dark, high-stakes romance between hunted lovers.' },
  { id: 'leviathan-wakes-james-s-a-corey', title: 'Leviathan Wakes', author: 'James S.A. Corey', genre: 'Science Fiction', isbn: '9781841499888', toRead: true, summary: 'A ship’s officer and a hard-boiled detective stumble onto a conspiracy that could ignite a solar-system-wide war.' },
  { id: 'scythe-neal-shusterman', title: 'Scythe', author: 'Neal Shusterman', genre: 'Science Fiction', coverId: 8184999, toRead: true, summary: 'In a world that conquered death, two teens apprentice to a scythe whose job is to permanently end lives — and keep the population in check.' },
  { id: 'children-of-time-adrian-tchaikovsky', title: 'Children of Time', author: 'Adrian Tchaikovsky', genre: 'Science Fiction', isbn: '9781447273288', toRead: true, summary: 'The last remnants of humanity find a terraformed planet — already inhabited by a spider civilization evolved by an ancient experiment.' },
  { id: 'the-legend-of-uh-aaron-n-hall', title: 'The Legend of Uh', author: 'Aaron N. Hall', genre: 'Fantasy', coverId: 15163140, isbn: '9798991097802', toRead: true, summary: 'An indie fantasy adventure following an unlikely hero thrust into a legend-making quest.' },
  { id: 'into-the-blue-emma-brodie', title: 'Into the Blue', author: 'Emma Brodie', genre: 'Contemporary Fiction', isbn: '9798217093700', toRead: true, summary: 'A woman leaves her old life behind for a summer on the water that reshapes everything she thought she wanted.' },
  { id: 'king-sorrow-joe-hill', title: 'King Sorrow', author: 'Joe Hill', genre: 'Horror', isbn: '9780062200600', toRead: true, summary: 'A group of college friends bound by a decades-old secret must reckon with the ancient evil they once summoned.' },
  { id: 'the-invisible-life-of-addie-larue-v-e-schwab', title: 'The Invisible Life of Addie LaRue', author: 'V.E. Schwab', genre: 'Fantasy', isbn: '9780765387561', toRead: true, summary: 'A woman makes a deal to live forever — as long as no one can ever remember her.' },
  { id: 'the-housemaid-freida-mcfadden', title: 'The Housemaid', author: 'Freida McFadden', genre: 'Thriller', coverId: 15105883, isbn: '9781803144375', toRead: true, summary: 'A live-in housemaid with a dark past finds her new employers hiding secrets of their own.' },
  { id: 'empire-of-silence-christopher-ruocchio', title: 'Empire of Silence', author: 'Christopher Ruocchio', genre: 'Science Fiction', isbn: '9780756413026', toRead: true, summary: 'A man who destroyed a sun recounts, from prison, how he became the empire’s most infamous war hero.' },
  { id: 'the-sword-of-kaigen-m-l-wang', title: 'The Sword of Kaigen', author: 'M.L. Wang', genre: 'Fantasy', coverId: 10447029, toRead: true, summary: 'A legendary warrior mother and her son face an invasion that forces her to reclaim the powers she buried long ago.' },
  { id: 'the-will-of-the-many-james-islington', title: 'The Will of the Many', author: 'James Islington', genre: 'Fantasy', isbn: '9781982141196', toRead: true, summary: 'A hidden heir enrolls in an elite academy inside an empire built on a system where the strong literally take power from the weak.' },
  { id: 'malice-john-gwynne', title: 'Malice', author: 'John Gwynne', genre: 'Fantasy', isbn: '9780230758452', toRead: true, summary: 'A crippled stable boy and a princess are drawn into an ancient war as a betrayed god plots his return.' },
  { id: 'the-shadow-of-the-gods-john-gwynne', title: 'The Shadow of the Gods', author: 'John Gwynne', genre: 'Fantasy', isbn: '9780356514185', toRead: true, summary: 'In a land where dead gods litter the earth, three strangers are pulled toward a war over the power still bleeding from their bones.' },
  { id: 'piranesi-susanna-clarke', title: 'Piranesi', author: 'Susanna Clarke', genre: 'Fantasy', coverId: 10226290, toRead: true, summary: 'A man living alone in an endless, labyrinthine house of statues and tides slowly uncovers the truth of who he really is.' },
  { id: 'lights-out-navessa-allen', title: 'Lights Out', author: 'Navessa Allen', genre: 'Romantasy', isbn: '9781638932239', toRead: true, summary: 'Book one of Into Darkness kicks off a dark, hunted romance between two people who shouldn’t trust each other.' },
  { id: 'remarkably-bright-creatures-shelby-van-pelt', title: 'Remarkably Bright Creatures', author: 'Shelby Van Pelt', genre: 'Contemporary Fiction', isbn: '9780063204157', toRead: true, summary: 'A widow forms an unlikely bond with a giant Pacific octopus who knows more about her family’s past than anyone realizes.' },
  { id: 'the-midnight-library-matt-haig', title: 'The Midnight Library', author: 'Matt Haig', genre: 'Contemporary Fiction', isbn: '9780525559474', toRead: true, summary: 'Between life and death, a woman finds a library of every life she could have lived.' },
  { id: 'jade-city-fonda-lee', title: 'Jade City', author: 'Fonda Lee', genre: 'Fantasy', coverId: 10401388, isbn: '9780316440882', toRead: true, summary: 'Rival crime families of magic-empowered jade warriors fight for control of a city on the brink of war.' },
  { id: 'eragon-christopher-paolini', title: 'Eragon', author: 'Christopher Paolini', genre: 'Fantasy', isbn: '9780375826696', toRead: true, summary: 'A farm boy who finds a dragon egg is swept into a rebellion against a tyrant king.' },
  { id: 'assassin-s-apprentice-robin-hobb', title: 'Assassin\'s Apprentice', author: 'Robin Hobb', genre: 'Fantasy', isbn: '9780553573398', toRead: true, summary: 'A royal bastard is secretly trained as an assassin for the throne that will never claim him as family.' },
  { id: 'the-way-of-kings-brandon-sanderson', title: 'The Way of Kings', author: 'Brandon Sanderson', genre: 'Fantasy', isbn: '9780765326355', toRead: true, summary: 'A slave turned reluctant leader, a scholar hiding a forbidden power, and a highprince at war open Sanderson’s Stormlight Archive.' },
  { id: 'babel-r-f-kuang', title: 'Babel', author: 'R.F. Kuang', genre: 'Fantasy', isbn: '9780063021426', toRead: true, summary: 'A Chinese orphan trained in Oxford’s translation magic must choose between the empire that raised him and the silver-powered system it built on stolen labor.' },
  { id: 'ender-s-game-orson-scott-card', title: 'Ender\'s Game', author: 'Orson Scott Card', genre: 'Science Fiction', isbn: '9780812550702', toRead: true, summary: 'A child genius is trained at a military academy in orbit to command the fleet that will save Earth from an alien enemy.' },
  { id: 'tress-of-the-emerald-sea-brandon-sanderson', title: 'Tress of the Emerald Sea', author: 'Brandon Sanderson', genre: 'Fantasy', coverId: 13143232, toRead: true, summary: 'A girl sails a sea of deadly magical spores to rescue the boy she loves from a sorceress.' },
  { id: 'the-name-of-the-wind-patrick-rothfuss', title: 'The Name of the Wind', author: 'Patrick Rothfuss', genre: 'Fantasy', isbn: '9780756404079', toRead: true, summary: 'A legendary figure living in hiding tells the true story of his rise from orphan to arcanist to living myth.' },
  { id: 'the-last-contract-of-isako-fonda-lee', title: 'The Last Contract of Isako', author: 'Fonda Lee', genre: 'Fantasy', coverId: 15154431, toRead: true, summary: 'A jade-powered enforcer takes on one final, impossible contract in Fonda Lee’s Green Bone universe.' },
  { id: 'sunrise-on-the-reaping-suzanne-collins', title: 'Sunrise on the Reaping', author: 'Suzanne Collins', genre: 'Science Fiction', isbn: '9781546171461', toRead: true, summary: 'Fifty years before Katniss, Haymitch Abernathy fights his own Hunger Games — and the Capitol he can never forgive.' },
  { id: 'butcher-blackbird-brynne-weaver', title: 'Butcher & Blackbird', author: 'Brynne Weaver', genre: 'Romantasy', toRead: true, summary: 'Two rival killers, forced into an annual game of one-upmanship, discover their fatal attraction might be more than professional.' },
  { id: 'dire-bound-sable-sorensen', title: 'Dire Bound', author: 'Sable Sorensen', genre: 'Romantasy', isbn: '9780316601382', toRead: true, summary: 'A woman bound to a cursed wolf shifter navigates a pack war and a bond neither of them chose.' },
  { id: 'the-correspondent-virginia-evans', title: 'The Correspondent', author: 'Virginia Evans', genre: 'Contemporary Fiction', isbn: '9780593798430', toRead: true, summary: 'A woman’s decades of letters to strangers, friends, and family reveal a life richer and stranger than anyone around her realized.' },
  { id: 'wild-dark-shore-charlotte-mcconaghy', title: 'Wild Dark Shore', author: 'Charlotte McConaghy', genre: 'Contemporary Fiction', coverId: 15146235, toRead: true, summary: 'A family guarding a remote seed vault on a storm-battered island takes in a mysterious castaway with secrets of her own.' },
  { id: 'red-city-marie-lu', title: 'Red City', author: 'Marie Lu', genre: 'Fantasy', toRead: true, summary: 'Marie Lu opens a new series in a world remade by dangerous alchemical power.' },
  { id: 'the-raven-scholar-antonia-hodgson', title: 'The Raven Scholar', author: 'Antonia Hodgson', genre: 'Fantasy', coverId: 15067081, toRead: true, summary: 'Six rival heirs compete in a brutal tournament to become the next ruler of an empire built on castes tied to sacred animal spirits.' },
  { id: 'wind-and-truth-brandon-sanderson', title: 'Wind and Truth', author: 'Brandon Sanderson', genre: 'Fantasy', isbn: '9781250319180', toRead: true, summary: 'The Stormlight Archive hurtles toward its Book Five climax as Roshar’s war against Odium reaches a breaking point.' },
  { id: 'bury-our-bones-in-the-midnight-soil-v-e-schwab', title: 'Bury Our Bones in the Midnight Soil', author: 'V.E. Schwab', genre: 'Fantasy', isbn: '9781250320520', toRead: true, summary: 'V.E. Schwab traces three women across centuries bound by the same hunger for immortality.' },
  { id: 'the-devils-joe-abercrombie', title: 'The Devils', author: 'Joe Abercrombie', genre: 'Fantasy', coverId: 15229572, toRead: true, summary: 'A ragtag crew of monsters — vampires, werewolves, and worse — is assembled to protect a fake princess on a deadly diplomatic mission.' },
  { id: 'the-strength-of-the-few-james-islington', title: 'The Strength of the Few', author: 'James Islington', genre: 'Fantasy', coverId: 15150800, toRead: true, summary: 'Book two of the Hierarchy series raises the stakes of Vis’s double life inside the empire’s brutal power structure.' },
]

const GENRES = [...new Set([...MY_BOOKS, ...TO_READ_BOOKS].map((b) => b.genre))].sort()
