// Matt's shelf — everything he's read (and is reading), pulled from his Goodreads export.
// `yearRead` shows a "Read 2025" badge; `reading: true` shows "Reading now";
// `rating` (1-5, his own Goodreads stars) drives the default sort.
const MY_BOOKS = [
  // — Red Rising saga —
  { id: 'red-rising', title: 'Red Rising', author: 'Pierce Brown', genre: 'Science Fiction', year: 2014, yearRead: 2025, isbn: '9780345539786', rating: 4,
    summary: 'A Red miner of Mars infiltrates the ruling Golds to burn their society down from the inside.',
    why: 'Ender meets Rome — the series everyone in tech is secretly reading. Start here.' },
  { id: 'golden-son', title: 'Golden Son', author: 'Pierce Brown', genre: 'Science Fiction', year: 2015, yearRead: 2025, isbn: '9780345539816', rating: 4,
    summary: 'Darrow rises through Gold society as civil war ignites across the solar system.',
    why: 'The rare book two that outdoes book one — betrayals land like body blows.' },
  { id: 'morning-star', title: 'Morning Star', author: 'Pierce Brown', genre: 'Science Fiction', year: 2016, yearRead: 2025, isbn: '9780345539847', rating: 4,
    summary: 'The Rising comes to a head as Darrow leads open rebellion against the Sovereign.',
    why: 'A finale that actually delivers — the original trilogy sticks the landing.' },
  { id: 'iron-gold', title: 'Iron Gold', author: 'Pierce Brown', genre: 'Science Fiction', year: 2018, yearRead: 2025, isbn: '9780425285916', rating: 3,
    summary: 'Ten years after the Rising, the new republic frays across four points of view.',
    why: 'What happens after the revolution wins — messier, darker, more ambitious.' },
  { id: 'dark-age', title: 'Dark Age', author: 'Pierce Brown', genre: 'Science Fiction', year: 2019, yearRead: 2025, isbn: '9780425285930', rating: 4,
    summary: 'War consumes Mars and Mercury in the saga’s most brutal installment.',
    why: 'Relentless and jaw-dropping — Brown at maximum intensity.' },
  { id: 'light-bringer', title: 'Light Bringer', author: 'Pierce Brown', genre: 'Science Fiction', year: 2023, yearRead: 2026, isbn: '9780425285978', rating: 4,
    summary: 'Darrow finds his way back to himself on the long road to a final reckoning with Atlas.',
    why: 'The series regains its soul — sets up the finale perfectly.' },

  // — Dungeon Crawler Carl —
  { id: 'dungeon-crawler-carl', title: 'Dungeon Crawler Carl', author: 'Matt Dinniman', genre: 'LitRPG', year: 2020, yearRead: 2025, coverId: 15143022, rating: 5,
    summary: 'Earth is demolished for an intergalactic reality-show dungeon; Carl and his ex’s cat fight through it live.',
    why: 'The funniest, angriest thing in sci-fi right now — a word-of-mouth phenomenon for a reason.' },
  { id: 'carls-doomsday-scenario', title: 'Carl’s Doomsday Scenario', author: 'Matt Dinniman', genre: 'LitRPG', year: 2020, yearRead: 2025, coverId: 11702962, rating: 4,
    summary: 'Carl and Donut hit the third floor and start weaponizing the dungeon’s own rules.',
    why: 'The satire sharpens and the game gets rigged — in both directions.' },
  { id: 'dungeon-anarchists-cookbook', title: 'The Dungeon Anarchist’s Cookbook', author: 'Matt Dinniman', genre: 'LitRPG', year: 2021, yearRead: 2025, coverId: 15233609, rating: 5,
    summary: 'The subway-line floor turns the crawl into full guerrilla warfare against the system.',
    why: 'Where the series reveals it has a plan — and a heart.' },
  { id: 'gate-of-the-feral-gods', title: 'The Gate of the Feral Gods', author: 'Matt Dinniman', genre: 'LitRPG', year: 2021, yearRead: 2025, coverId: 15232581, rating: 4,
    summary: 'Castles, submarines, and bubble-dwelling gods on a floor built to break parties.',
    why: 'Peak chaos-engineering from Carl — and Donut steals every scene.' },
  { id: 'butchers-masquerade', title: 'The Butcher’s Masquerade', author: 'Matt Dinniman', genre: 'LitRPG', year: 2022, yearRead: 2025, coverId: 15231958, rating: 5,
    summary: 'The hunting-ground floor invites the galaxy’s elite to hunt crawlers — badly, it turns out.',
    why: 'Fan-favorite for a reason: the masquerade sequence is an all-timer.' },
  { id: 'eye-of-the-bedlam-bride', title: 'The Eye of the Bedlam Bride', author: 'Matt Dinniman', genre: 'LitRPG', year: 2023, yearRead: 2025, coverId: 15231488, rating: 4,
    summary: 'Carl faces the faction wars while a reality-warping god takes a personal interest.',
    why: 'The stakes go cosmic without losing the jokes.' },
  { id: 'this-inevitable-ruin', title: 'This Inevitable Ruin', author: 'Matt Dinniman', genre: 'LitRPG', year: 2024, yearRead: 2025, coverId: 15142977, rating: 4,
    summary: 'The war floor: every faction, every grudge, and Carl’s long game all collide.',
    why: 'The series’ biggest swing yet — and it connects.' },
  { id: 'parade-of-horribles', title: 'A Parade of Horribles', author: 'Matt Dinniman', genre: 'LitRPG', year: 2026, yearRead: 2026, rating: 4,
    summary: 'The crawl barrels toward its endgame as the ninth floor opens.',
    why: 'Book eight of the crawl — the end is in sight.' },

  // — Bobiverse —
  { id: 'we-are-legion', title: 'We Are Legion (We Are Bob)', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2016, yearRead: 2025, isbn: '9781680680584', rating: 5,
    summary: 'A software engineer wakes up as a self-replicating space probe and starts forking.',
    why: 'The most engineer-brained sci-fi ever written — every dev sees themselves in Bob.' },
  { id: 'for-we-are-many', title: 'For We Are Many', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2017, yearRead: 2025, coverId: 11329842, rating: 4,
    summary: 'The Bobs spread across star systems while an alien threat starts eating colonies.',
    why: 'Scaling problems, literally — the Bobiverse grows up.' },
  { id: 'all-these-worlds', title: 'All These Worlds', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2017, yearRead: 2026, coverId: 12750210, rating: 4,
    summary: 'The war with the Others comes to a head as humanity’s last colonies hang in the balance.',
    why: 'Closes the first arc with a genuinely satisfying engineering victory.' },
  { id: 'heavens-river', title: 'Heaven’s River', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2020, yearRead: 2026, coverId: 10522898, rating: 5,
    summary: 'A rescue mission inside a 900-million-mile megastructure tests what the Bobs have become.',
    why: 'Big Dumb Object sci-fi done right, with a civil war brewing among the Bobs themselves.' },
  { id: 'not-till-we-are-lost', title: 'Not Till We Are Lost', author: 'Dennis E. Taylor', genre: 'Science Fiction', year: 2024, yearRead: 2026, coverId: 14926951,
    summary: 'The Bobs scatter to new frontiers as humanity’s diaspora hits growing pains.',
    why: 'The Bobiverse keeps finding new problems worth solving.' },

  // — Empyrean —
  { id: 'fourth-wing', title: 'Fourth Wing', author: 'Rebecca Yarros', genre: 'Fantasy', year: 2023, yearRead: 2025, isbn: '9781649374042',
    summary: 'A fragile scribe is forced into a war college where dragon riders are made — or killed.',
    why: 'The romantasy juggernaut — read it to understand what took over publishing.' },
  { id: 'iron-flame', title: 'Iron Flame', author: 'Rebecca Yarros', genre: 'Fantasy', year: 2023, yearRead: 2025, isbn: '9781649374172',
    summary: 'Violet learns the war she trained for is built on lies — and the real enemy is older.',
    why: 'Doubles down on the conspiracies behind the dragons.' },
  { id: 'onyx-storm', title: 'Onyx Storm', author: 'Rebecca Yarros', genre: 'Fantasy', year: 2025, yearRead: 2025, isbn: '9781649374189',
    summary: 'Violet hunts allies beyond the wards while everything at Basgiath unravels.',
    why: 'The biggest launch in publishing history — and a cliffhanger to match.' },

  // — Mistborn —
  { id: 'mistborn', title: 'Mistborn: The Final Empire', author: 'Brandon Sanderson', genre: 'Fantasy', year: 2006, yearRead: 2026, isbn: '9780765350381', rating: 5,
    summary: 'A street thief discovers she’s Mistborn and joins a crew planning to rob and topple an immortal god-emperor.',
    why: 'The best magic system in fantasy plus an Ocean’s Eleven heist — Sanderson’s perfect entry point.' },
  { id: 'well-of-ascension', title: 'The Well of Ascension', author: 'Brandon Sanderson', genre: 'Fantasy', year: 2007, yearRead: 2026, isbn: '9780765356130', rating: 4,
    summary: 'The crew won — now they have to govern, under siege from three armies at once.',
    why: 'What happens after you win the revolution — the founder’s dilemma in fantasy form.' },
  { id: 'hero-of-ages', title: 'The Hero of Ages', author: 'Brandon Sanderson', genre: 'Fantasy', year: 2008, reading: true, isbn: '9780765356147',
    summary: 'The world itself is ending, and every clue from two books snaps into place.',
    why: 'One of the great endings in fantasy — every setup pays off.' },

  // — Throne of Glass —
  { id: 'throne-of-glass', title: 'Throne of Glass', author: 'Sarah J. Maas', genre: 'Fantasy', year: 2012, yearRead: 2026, isbn: '9781619630345',
    summary: 'An imprisoned assassin competes to become the king’s champion while something stalks the castle.',
    why: 'The series that built Maas’s empire — starts fun, goes epic.' },
  { id: 'crown-of-midnight', title: 'Crown of Midnight', author: 'Sarah J. Maas', genre: 'Fantasy', year: 2013, reading: true, isbn: '9781619630628',
    summary: 'Celaena serves the king she despises while keeping deadly secrets from everyone she loves.',
    why: 'Where the series shows its real cards — the twist recontextualizes everything.' },

  // — standalones & classics —
  { id: 'project-hail-mary', title: 'Project Hail Mary', author: 'Andy Weir', genre: 'Science Fiction', year: 2021, yearRead: 2026, isbn: '9780593135204', rating: 5,
    summary: 'A lone astronaut wakes with amnesia on a last-ditch mission to save the sun — and finds an unlikely ally.',
    why: 'The most-recommended novel in tech since The Martian — problem-solving as a love language.' },
  { id: 'dark-matter', title: 'Dark Matter', author: 'Blake Crouch', genre: 'Science Fiction', year: 2016, yearRead: 2025, isbn: '9781101904220',
    summary: 'A physics professor is abducted into the multiverse by the man he could have been.',
    why: 'A thriller about the roads not taken — every ambitious person’s what-if, weaponized.' },
  { id: 'hitchhikers-guide', title: 'The Hitchhiker’s Guide to the Galaxy', author: 'Douglas Adams', genre: 'Science Fiction', year: 1979, yearRead: 2025, isbn: '9780345391803', rating: 4,
    summary: 'Earth is demolished for a hyperspace bypass; Arthur Dent survives with a towel and a very unhelpful guidebook.',
    why: 'The founding text of engineer humor — Don’t Panic remains the best product advice ever shipped.' },
  { id: 'nineteen-eighty-four', title: '1984', author: 'George Orwell', genre: 'Classics', year: 1949, yearRead: 2025, isbn: '9780451524935', rating: 4,
    summary: 'Winston Smith commits the crime of thinking for himself inside a total surveillance state.',
    why: 'Still the sharpest lens on surveillance, language, and power — rereads differently every decade.' },
  { id: 'fellowship-of-the-ring', title: 'The Fellowship of the Ring', author: 'J.R.R. Tolkien', genre: 'Fantasy', year: 1954, yearRead: 2025, isbn: '9780547928210', rating: 4,
    summary: 'A hobbit inherits a ring that must be carried into the heart of enemy territory and destroyed.',
    why: 'The source code for all modern fantasy — everything since is a fork.' },
  { id: 'harry-potter-series', title: 'Harry Potter (complete series)', author: 'J.K. Rowling', genre: 'Fantasy', year: 1997, yearRead: 2025, isbn: '9780590353427', rating: 4,
    summary: 'Seven years at Hogwarts, from cupboard under the stairs to the Battle of Hogwarts.',
    why: 'The shared universe of an entire generation — worth rereading as an adult.' },
  { id: 'tomorrow-x3', title: 'Tomorrow, and Tomorrow, and Tomorrow', author: 'Gabrielle Zevin', genre: 'Literary Fiction', year: 2022, yearRead: 2025, coverId: 12859975, rating: 4,
    summary: 'Two friends build video games together across thirty years of love, grief, and creative partnership.',
    why: 'The best novel ever written about creative collaboration and shipping things with people you love.' },
  { id: 'atmosphere', title: 'Atmosphere', author: 'Taylor Jenkins Reid', genre: 'Literary Fiction', year: 2025, yearRead: 2026, coverId: 15098710, rating: 5,
    summary: 'A 1980s shuttle astronaut finds love and catastrophe in NASA’s golden age.',
    why: 'Reid turns the space program into her most emotional book yet.' },
  { id: 'lightlark', title: 'Lightlark', author: 'Alex Aster', genre: 'Fantasy', year: 2022, yearRead: 2026, coverId: 12917631,
    summary: 'Six cursed rulers compete in a deadly centennial game where only one curse can be broken.',
    why: 'The BookTok phenomenon that became a bidding war — a fast, twisty palate cleanser.' },
  { id: 'blood-over-bright-haven', title: 'Blood Over Bright Haven', author: 'M.L. Wang', genre: 'Fantasy', year: 2023, yearRead: 2026, coverId: 15090335, rating: 4,
    summary: 'The first woman admitted to a magical academy discovers the atrocity powering her city’s magic.',
    why: 'A standalone gut-punch about institutions and the cost of looking away — dark-academia done right.' },
  { id: 'end-the-fed', title: 'End the Fed', author: 'Ron Paul', genre: 'Economics', year: 2009, yearRead: 2026, coverId: 6255029, rating: 4,
    summary: 'Paul’s case against central banking: how the Federal Reserve distorts money, credit, and the business cycle.',
    why: 'Agree or not, it’s the argument behind half of crypto’s founding ethos.' },

  // — added from Matt's Goodreads export (2026-07) —
  { id: 'dune', title: 'Dune', author: 'Frank Herbert', genre: 'Science Fiction', year: 1965, isbn: '9780593099322', rating: 4,
    summary: 'Paul Atreides inherits a desert planet that controls the most valuable substance in the universe.',
    why: 'The best-selling sci-fi novel ever — politics, ecology, and empire in one book; a favorite of Musk and Bezos alike.' },
  { id: 'dune-messiah', title: 'Dune Messiah', author: 'Frank Herbert', genre: 'Science Fiction', year: 1969, isbn: '9780593098233', rating: 3,
    summary: 'Twelve years into Paul\u2019s reign, the jihad done in his name becomes a prison he cannot escape.',
    why: 'Herbert\u2019s deliberate answer to book one: what victory costs the victor.' },
  { id: 'three-body-problem', title: 'The Three-Body Problem', author: 'Liu Cixin', genre: 'Science Fiction', year: 2008, isbn: '9780765382030', rating: 5,
    summary: 'A signal sent to the stars during the Cultural Revolution invites a civilization with nothing to lose.',
    why: 'Obama and half of Silicon Valley recommend it — first contact as game theory at civilizational scale.' },
  { id: 'the-martian', title: 'The Martian', author: 'Andy Weir', genre: 'Science Fiction', year: 2011, isbn: '9780804139021', rating: 5,
    summary: 'An astronaut stranded on Mars sciences his way through every problem between him and rescue.',
    why: 'Pure engineering optimism — the book that made problem-solving a genre.' },
  { id: 'ready-player-one', title: 'Ready Player One', author: 'Ernest Cline', genre: 'Science Fiction', year: 2011, isbn: '9780307887436',
    summary: 'A global treasure hunt inside a virtual world where the prize is control of the OASIS itself.',
    why: 'The book every VR and metaverse pitch deck secretly references.' },
  { id: 'armada', title: 'Armada', author: 'Ernest Cline', genre: 'Science Fiction', year: 2015, isbn: '9780804137256',
    summary: 'A gamer discovers the alien-invasion game he\u2019s mastered is a training simulator for the real thing.',
    why: 'A popcorn homage to The Last Starfighter — fast, nostalgic fun.' },
  { id: 'artemis', title: 'Artemis', author: 'Andy Weir', genre: 'Science Fiction', year: 2017, isbn: '9780553448122',
    summary: 'A smuggler on the Moon\u2019s only city takes one job too big and has to out-engineer the fallout.',
    why: 'Weir\u2019s heist-on-the-Moon — lighter than his other books but built on the same real physics.' },
  { id: 'two-towers', title: 'The Two Towers', author: 'J.R.R. Tolkien', genre: 'Fantasy', year: 1954, isbn: '9780547928203', rating: 4,
    summary: 'The fellowship is broken: Rohan rides to war while Frodo follows a treacherous guide toward Mordor.',
    why: 'The middle passage that invented the epic-fantasy war story.' },
  { id: 'return-of-the-king', title: 'The Return of the King', author: 'J.R.R. Tolkien', genre: 'Fantasy', year: 1955, isbn: '9780547928197', rating: 4,
    summary: 'The war for Middle-earth ends at the Black Gate — and on the slopes of Mount Doom.',
    why: 'The ending every fantasy series since has been chasing.' },
  { id: 'operation-bounce-house', title: 'Operation Bounce House', author: 'Matt Dinniman', genre: 'LitRPG', year: 2026, yearRead: 2026, isbn: '9780593820308', rating: 3,
    summary: 'A standalone romp in the Dungeon Crawler Carl universe.',
    why: 'For DCC completionists waiting on the next main course.' },
  { id: 'eleven-twenty-two-sixty-three', title: '11/22/63', author: 'Stephen King', genre: 'Thriller', year: 2011, isbn: '9781451627282', rating: 4,
    summary: 'A teacher finds a doorway to 1958 and spends five years trying to stop the Kennedy assassination.',
    why: 'King\u2019s best-loved late-career book — time travel with real stakes and a broken heart.' },
  { id: 'girl-with-the-dragon-tattoo', title: 'The Girl with the Dragon Tattoo', author: 'Stieg Larsson', genre: 'Thriller', year: 2005, isbn: '9780307454546', rating: 4,
    summary: 'A disgraced journalist and a brilliant hacker unravel a forty-year-old disappearance in a family of industrialists.',
    why: 'The thriller that made forensic investigation cool — and Lisbeth Salander iconic.' },
  { id: 'subtle-art', title: 'The Subtle Art of Not Giving a F*ck', author: 'Mark Manson', genre: 'Self-Help', year: 2016, isbn: '9780062457714',
    summary: 'You have a finite number of f*cks to give — choose the few things worth caring about and let the rest go.',
    why: 'The anti-self-help book: values over positivity, chosen problems over comfort.' },
]


const GENRES = [...new Set(MY_BOOKS.map((b) => b.genre))].sort()
